### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by janisozaur**
includes #4 already.

### CODE REVIEW

**Comment by X123M3-256** [comment]
C99 math.h doesn't define M_PI and I couldn't get it to compile without  redefining it. Can you make sure this still compiles if you pass --std=c99?

**Comment by janisozaur** [comment]
There you go

**Comment by X123M3-256** [comment]
Seems to work. I'll merge this now

**Comment by X123M3-256** [comment]
How would I add a new library to the CMake file? I see references to GTK and JANSSON, but I'm not sure where those symbols come from - does it just look for a file named libjansson.a in the linker path?

I'm asking because I'm planning to make the code in dat.c and renderer.c into seperate libraries so I can stop copying and pasting the code between projects.

**Comment by janisozaur** [comment]
You'd have to wrap these files into a library target, then link this target to the executable.

Currently I'm using `pkg-config` to supply all the information required to link it, but you of course wouldn't want to do that.

Have a look at https://cmake.org/cmake/help/v3.0/command/add_library.html

**Comment by X123M3-256** [comment]
OK, thanks. I should probably use CMake for the library code as well, which means I really need to learn how to use it. I'll leave model.c and animation.c as part of this project for now but I'm thinking of making those a library eventually.

**Pull request merged**
