### PR TITLE
Little update

### PR DESCRIPTION
**Pull request by spacek531**
it's not perfect, but it is...

* adding numerous missing properties to the json
* adding selfsame properties to the GUI
* adding a bunch more flags editable with the GUI
* fix the off-by-one error with vehicle flags property and automatically convert legacy save files
* re-arrange GUI so it's friendly to landscape-oriented screens

Todo:

[  ] merge `ride_header_t` into `project_t` and `car_t` into `car_settings_t` for better WYSIWSG programming (i.e. not having nearly-duplicate types)
[  ] finish refactoring serialize and deserialize functions to use `try_catch_int` and `serialize_int_dict`
[  ] embiggen the model editor pane so all color swatches are selectable
[  ] formatting

stretch goals:
[  ] create default colors editor
[  ] animation type selector
[  ] get spinning cars working
[  ] make the 3 swinging flags do things (and make the interface more intuitive)
[  ] more properties added to JSON
[  ] more properties added to GUI

### CODE REVIEW

**Comment by X123M3-256** [comment]
Sounds good. I'll merge it tomorrow because there are conflicts needing resolution and I don't have time tonight.

**Comment by X123M3-256** [comment]
I've merged it. It seems the new additions prevent any of my old files from loading so I couldn't really test it, but it does compile - you might want to check that the merge conflicts didn't break anything.

**Comment by spacek531** [comment]
I don't know how to find merge conflicts. I tested my latest build (no changes since this PR) with even my oldest ride (scenic railway) and it loaded just fine.

**Comment by X123M3-256** [comment]
> I don't know how to find merge conflicts

It tells you there are merge conflicts when you submit the PR. I'm not sure what the cause was - usually, this would happen if one of the files you changes has been modified by someone else in the meantime, but the last commits to this repo were also from you.

I've fixed the merge conflicts and merged the PR, but I haven't checked that the program still works (I've only checked that it compiles and runs). I can't be sure I didn't break something while fixing the conflicts.

**Pull request merged**
